#+ID: 0493fd15-8aeb-45cb-b8d9-2046ccfab2da
#+STARTUP: overview

Start the development environment with:

#+begin_src bash
./bin/env-start
#+end_src

Once started, an editor opens this very file. Its basic commands are:
- Move the point using the arrows.
- Place the point on a section and press <tab> to unfold it.
- Click on a link to view references to it.
- A link that starts with "⊙" defines a location, /i.e./ it says "here".
- A link that starts with "→" defines a reference to a location, /i.e./ it says "got to the
  referenced location".
- Quit the editor using C-x C-c.
- It means: press on <control> and "x", then: press on <control> and "c".

To understand /what/ ~./bin/env-start~ is supposed to do, you may consult its /spec/, /i.e./
/specification/, which is referenced from its source code. See: [[ref:b80c22c9-2eed-4eea-a469-136e7666ea96]]. To understand /how/ it
does what it is supposed to do, read the source code.

To contribute, see: [[ref:5513764b-8595-4e2d-bcf9-8e8214ee901b][Contributing]].

The remaining of the document describes or points to explanations regarding parts of the
directory.

- application :: The application is the program we are building.
- frontend/ :: This directory stores the frontend of the application.
- backend/ :: This directory stores the code for the backend of the application.
- doc/ :: This directory stores various pieces of documentations.
- bin/ :: This directory stores executables.
- etc/ :: This directory stores various configuration files for Bash, Guix, …
- certs/ :: This directory stores certificates used for testing purposes. TODO(a4a3): should be under etc/
- deployment/ :: This directory stores ways to deploy operating systems to VPS.
- emacs.d/ :: This directory stores Emacs configuration files, the main =$EDITOR=.
- os/ :: This directory stores operating systems specifications.
- image/ :: This directory stores various disk images of operating systems of operating
  systems for testing purposes.
- ssh/ :: This directory stores various SSH related files. TODO(6856): should be under etc/
- vm/ :: This directory stores files necessary for VM execution. TODO(7990): should be
  somewhere under /run.
