#+OPTIONS: author:nil
#+PROPERTY: header-args:bash :exports both :results output raw :wrap example

* Developer
:PROPERTIES:
:ID:       b6f1f176-25ce-424f-9386-29a5115717e6
:END:

The developer knows the implementation: what it can and cannot do, how it operates,
and why it was built that way. He provides feedback and implementations to the
[[ref:87e740ec-6036-4154-968d-625196f90ee4][architect]].

- The Developer owns the *implementation*, *quality*, and *delivery* of product features
  while following the architecture and standards to support what the Sales Rep can
  sell.

- If implementation reveals flaws in the architecture or any other aspects, then
  these should be reported.

- If implementation optimization opportunities arise from implementation, then these
  should be reported.

- Every developer is:
  - Identified: commits are signed. Example: [[ref:73a7c491-ef86-4523-bfad-f024fef4fa07][Identification]].
  - Maintains a list of iterations to track time and other critical
    feedbacks. Example: [[ref:e3eff8db-1d6e-4e93-8820-4e8168678ade][Iteration]]

** Developers

- [[ref:1446c391-2c77-4290-be29-b4fa76a751c9][PHF]]
