* Backlog
:PROPERTIES:
:ID:       90abac79-d226-4de2-9174-9df6c48c25c0
:END:

A backlog is a list of [[ref:3427d8a4-4fc0-4d98-a8f7-59ac1399a9dc][tasks]] organized top to bottom by priority. From the backlog,
we know what needs to be done, and who works on what.

** Tasks
*** DONE Add Claude

- Objective :: Having claude in its own container sending PRs.
- Test :: add bin/,todos that lists todos in the project.

*** DONE M-p ↦ Path of heading copied to clipboard
**** Objective

Helper to easy commit editing.

*** DONE Refine the contributing guide
*** DONE Fix ,synchronize-with-upstream
**** Objective

Fix [[ref:119d5773-63cc-4add-b4d2-d5001b367677][actor]] so that it implements: [[ref:c5d59ff9-cc78-4f98-a7f6-22d19c39caff][Specification]].

*** DONE ,synchronize-with-upstream
**** Objective

Provide a script to automate the synchronization step of [[ref:5513764b-8595-4e2d-bcf9-8e8214ee901b][Contributing]].

*** DONE Fix contributing cycle
**** Objective

Ensure that the history is linear

*** DONE Test contributing cycle
:PROPERTIES:
:ID: 70b6d0d4-20b1-44bd-ba93-d793339d6a3d
:OWNER: phf
:END:

**** Objective

Test [[ref:5513764b-8595-4e2d-bcf9-8e8214ee901b][Contributing]]

*** DONE Task
:PROPERTIES:
:ID:       3427d8a4-4fc0-4d98-a8f7-59ac1399a9dc
:OWNER: phf
:END:

**** Objective

Define what we mean by a =Task=.

**** Structure

An example of a Task is:

#+begin_src org
,* TODO Dark theme
:PROPERTIES:
:ID: 70b6d0d4-20b1-44bd-ba93-d793339d6a3d
:OWNER: nobody
:END:

,** Objective

Let the user activate a dark theme.

,** Test

Once logged in, the user may click on a dark them icon in the upper-right corner of his
profile to activate it.
#+end_src

The =TODO= above is a =State=. A =State= may be one of:
- TODO :: meaning that the task is not implemented and no-one is working on it.
- DOING :: meaning that the task is not implemented and someone is working on it.
- DONE :: meaning that the task is implemented.
- FAILED :: meaning that the task is not implemented for some reason described within the task and no one is working on it.

A task contains at least one section: =Objective= which describes what should be
accomplished. Other sections may be added depending on the task at hand, maybe: =Plan=,
=Test=, =Why=, =Discussion=, =Result=, and so on.

A task may have an owner which is referenced by its identifier. =nobody= means that
no-one is the owner.

So, the structure of a Task may be viewed as follows:

|-----------+---------+--------------------------------------|
| Property  | Type    | Example                              |
|-----------+---------+--------------------------------------|
| name      | String  | Dark theme                           |
| id        | UUIDv4  | 70b6d0d4-20b1-44bd-ba93-d793339d6a3d |
| state     | State   | TODO                                 |
| owner     | OwnerId | nobody                               |
| Objective | Section | see above.                           |
| …         | Section | …                                    |
|-----------+---------+--------------------------------------|

**** Assign a task to someone

For Alice to assign Bob to a task, it is enough for Alice to fork the repository, set
Bob as the owner of the task, /i.e./ set the property =:OWNER:= to =bob= or whatever
identifier is used by Bob and its state to =DOING=, and send a PR. Most likely, Bob
will assign himself to tasks.
