* Type
:PROPERTIES:
:ID:       1f6eeb40-6e6b-4e19-9d5d-23af3858023d
:END:

- A new type (or type family) of computational objects is introduced as in
  [[ref:76a63511-31c3-4de7-90e9-47358a43599b][transpiler.org]].

- It defines in order:
  1. a module
  2. imported modules
  3. private implementations
  4. zero or more public constructors
  5. an optional public eliminator
  6. optional functions that take an instance of T as their first argument, a.k.a. the /API/.
  7. other public functions, /e.g./ predicates.

** Documentation

- The *necessary* documentation lives in:
  - the first section, which describes what this type *represents*, /i.e./ what is its *semantics*.
  - the public functions.

** Notation

- Constructors are functions named as follows: T#mk : … → T, where "mk" is the name
  of some particular constructor.

- To use an instance t : T, APIs are procedures (they may have side effects, raise
  exceptions, /etc./) of the form T#name : T … → C.

- More generally, a module for T may offer functions of the form Any … → C, /e.g./
  predicates. These are exported using the same convention, /e.g./ T#? : Any → Boolean.

- A premise of the form x :≡ f(...) with no type annotation asserts termination of f(…)
  and binds the result to x. In practice, termination is not always guaranteed because of
  exceptions, errors, …

** Specification

- A specification — /i.e./ what a given algorithm is supposed to do — uses a
  Gentzen-style natural deduction format: a /Premises/ section listing the typing
  context and a /Conclusion/ section stating what holds if all premises are satisfied
  and all computations terminate.

- The Conclusion is a *partial correctness* statement: it specifies what is supposed to
  have happened *IF EVERYTHING WENT AS PLANNED*.
