* Backlog
:PROPERTIES:
:ID:       90abac79-d226-4de2-9174-9df6c48c25c0
:END:

A backlog is a list of [[ref:3427d8a4-4fc0-4d98-a8f7-59ac1399a9dc][tasks]] organized top to bottom by priority.

** DOING A beautiful clock
:PROPERTIES:
:ID:       44ceb8c1-0c1b-4497-a041-dab8548af84e
:OWNER: phf
:END:

So, we need to display [[ref:a3f603d3-c122-4de6-b587-e7095d052831][beautiful clocks]].

It should be enough to update the [[ref:037f98a3-fddc-4390-81fd-c0cc48c19d13][clock liveview]] so that something like a wall clock
is displayed using two needles, one for the seconds and one for the minutes since we
do not expect the clocks to run for hours.

** DONE Task template
:PROPERTIES:
:ID:       3427d8a4-4fc0-4d98-a8f7-59ac1399a9dc
:END:

A task can be in these states:
- TODO: no-one is working on it.
- DOING: someone is working on it.
- DONE: it has been completed successfully and has been merged.

To mark someone as the owner, add the :OWNER: property and give it your id.

A task content SHOULD answer to, at least, these questions:
- What should be done.
- If any, guidelines on how it should be done.
- If any, guidelines on how it should be tested.
- If any, other properties that must be satisfied.

* Local Variables                                                  :noexport:

# Local Variables:
# eval: (add-hook 'before-save-hook #'whitespace-cleanup nil t)
# eval: (add-hook 'after-save-hook #'lar-reload nil t)
# org-confirm-babel-evaluate: nil
# fill-column: 85
# End:
